#!/bin/bash

BUNDLE=/home/mvdw/.vim/bundle

if [[ -d $BUNDLE ]]; then
    for VAL in $BUNDLE/*; do
        if [[ -d $VAL/.git ]]; then
            cd $VAL
            if [[ -d .git ]]; then
                echo -e "$VAL - $(git pull)" 

            fi
            cd ..
        fi
    done
fi 
