#!/bin/env bash
#  Author: Mirko van der Waal 
#  Mail: <mvdw at airmail dot cc>
#  Distributed under terms of the GNU2 license.
#
#  Copyright (C) 2015 
#   
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#   
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#   
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, see <http://www.gnu.org/licenses/>.

while read DATA; do
    if   [[ "$DATA" == "MUSIC" ]]; then
		CMD="urxvt -e 'ncmpcpp'"
	elif [[ "$DATA" == "NETWORK" ]]; then
		CMD="urxvt -e 'nmtui'"
	elif [[ "$DATA" == "VOLUME" ]]; then
		CMD="urxvt -e 'alsamixer'"
	else
        CMD="notify-send 'Fail'"
	fi
	echo "$CMD &"
done
