#!/bin/env bash
#  Author: Mirko van der Waal 
#  Mail: <mvdw at airmail dot cc>
#  Distributed under terms of the GNU2 license.
#
#  Copyright (C) 2015 
#   
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#   
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#   
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, see <http://www.gnu.org/licenses/>.



COLOR_PASSIVE_BG='#FF170F0D'
COLOR_PASSIVE_FG='#FFAF652F'

COLOR_FOCUSED_BG='#FF170F0D'
COLOR_FOCUSED_FG='#FFC8B55B'

COLOR_BACKGROUND='#FF170F0D'
COLOR_FOREGROUND='#FFC8B55B'

COLOR_STATUS_BG='#FF170F0D'
COLOR_STATUS_FG='#FFC8B55B'

COLOR_ICON_BG='#FF170F0D'
COLOR_ICON_FG='#FFAF652F'
