#!/bin/bash

while read DATA; do
    if   [[ "$DATA" == "MUSIC" ]]; then
		CMD="urxvt -e 'ncmpcpp'"
	elif [[ "$DATA" == "NETWORK" ]]; then
		CMD="urxvt -e 'nmtui'"
	elif [[ "$DATA" == "VOLUME" ]]; then
		CMD="urxvt -e 'alsamixer'"
	else
        CMD="notify-send 'Fail'"
	fi
	echo "$CMD &"
done
