#! /bin/sh
#
# Example panel for LemonBoy's bar

. panel_colors

num_mon=$(bspc query -M | wc -l)

while read -r LINE; do
    case $LINE in
		# Order Matters
		H*) CASE_MUSIC="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${LINE#?} %{B-}%{F-}"
            ;;
		N*) CASE_NETWORK="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${LINE#?}%{B-}%{F-}"
			;;
		V*) CASE_VOLUME="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${LINE#?} %{B-}%{F-}"
			;;
		B*) CASE_BATTERY="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${LINE#?} %{B-}%{F-}"
			;;
		S*) CASE_CLOCK="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${LINE#?} %{B-}%{F-}"
			;;
		W*) CASE_WINDOW=""
			IFS=':'
			set -- ${LINE#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				monocle=$(bspc control --get-status | grep -ci "LM")
				case $item in
					# M*)
						# # active monitor
						# if [ $num_mon -gt 1 ] ; then
							# CASE_WINDOW="$CASE_WINDOW %{F$COLOR_ACTIVE_MONITOR_FG} %{F-}  "
						# fi
						# ;;
					# m*)
						# # inactive monitor
						# if [ $num_mon -gt 1 ] ; then
							# CASE_WINDOW="$CASE_WINDOW %{F$COLOR_INACTIVE_MONITOR_FG} %{F-}  "
						# fi
						# ;;
					O*)
						# focused occupied desktop
						name=""
						CASE_WINDOW="${CASE_WINDOW}%{F$COLOR_FOCUSED_OCCUPIED_FG} ${name} %{F-}"
						;;
					F*)
						# focused free desktop
						name=""
						CASE_WINDOW="${CASE_WINDOW}%{F$COLOR_FOCUSED_FREE_FG} ${name} %{F-}"
						;;
					U*)
						# focused urgent desktop
						name=""
						CASE_WINDOW="${CASE_WINDOW}%{F$COLOR_FOCUSED_URGENT_FG} ${name} %{F-}"
						;;
					o*)
						# occupied desktop
						# 
						name=""
						CASE_WINDOW="${CASE_WINDOW}%{F$COLOR_OCCUPIED_FG} ${name} %{F-}"
						;;
					f*)
						# free desktop
						name=""
						CASE_WINDOW="${CASE_WINDOW}%{F$COLOR_FREE_FG} ${name} %{F-}"
						;;
					u*)
						# urgent desktop
						name=""
						CASE_WINDOW="${CASE_WINDOW}%{F$COLOR_URGENT_FG} ${name} %{F-}"
						;;
					L*)
						# layout
						if [ "$name" == "T" ]
						then
							name=""
						elif [ "$name" == "M" ]
						then
							name=""
						fi
						CASE_WINDOW="%{B$COLOR_LAYOUT_BG}%{B-}$CASE_WINDOW"
						;;
				esac
				shift
			done
			;;
	esac

    # We link everything to a shorthand variable to maintain overview.
    WM="${CASE_WINDOW}"
    CL="${CASE_CLOCK}"
    MU="%{A:MUSIC:}${CASE_MUSIC}%{A}"
    VO="%{A:VOLUME:}${CASE_VOLUME}%{A}"
    BA="${CASE_BATTERY}"
    NE="%{A:NETWORK:}${CASE_NETWORK}%{A}"

    printf "%s\n" "${WM}%{c}${CL}%{r}${MU}${VO}${BA}${NE}  "
done






































